# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pillager < Formula
  desc "Pillage filesystems for sensitive information"
  homepage "https://github.com/brittonhayes/pillager"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.1/pillager_0.7.1_Darwin_x86_64.tar.gz"
      sha256 "9a91d146e313033a878eb7b0ad12c4aa4f7e9a56556c4bef85ae01b44d20703b"

      def install
        bin.install "pillager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.1/pillager_0.7.1_Darwin_arm64.tar.gz"
      sha256 "6f3121b4f7f61b92955a24e48e5dfc64b4386ea22d699cd31fc5792664fe1ff5"

      def install
        bin.install "pillager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.1/pillager_0.7.1_Linux_x86_64.tar.gz"
      sha256 "1eb8a338d1cabfe6186c8ebdd8b913cfb202cb2824bb179e813b4c37c9275050"

      def install
        bin.install "pillager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.1/pillager_0.7.1_Linux_arm64.tar.gz"
      sha256 "d104480bbd81c6ffaeabd734b3e996c14a146663a40b4c0277a749d1036b6f18"

      def install
        bin.install "pillager"
      end
    end
  end
end
