# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pillager < Formula
  desc "Pillage filesystems for sensitive information"
  homepage "https://github.com/brittonhayes/pillager"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.2/pillager_0.7.2_Darwin_arm64.tar.gz"
      sha256 "e2b6a48bfe05a6edce7eaf687074cd6d081c47fe7da0c2791a03a635435551b9"

      def install
        bin.install "pillager"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.2/pillager_0.7.2_Darwin_x86_64.tar.gz"
      sha256 "9ab11c60c628102c71e9b24fd16dc68cbbcf0319ddee65b3794bd1889e4e0f42"

      def install
        bin.install "pillager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.2/pillager_0.7.2_Linux_x86_64.tar.gz"
      sha256 "eb25cb46b88d375f9e6353d8d5e235d2fbbc800a38f1b945b09fc5241ac19aeb"

      def install
        bin.install "pillager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brittonhayes/pillager/releases/download/v0.7.2/pillager_0.7.2_Linux_arm64.tar.gz"
      sha256 "cd7670dbfd6eeceffaa959028634edc06f0871021b3d2dc832bdeef72490288c"

      def install
        bin.install "pillager"
      end
    end
  end
end
